naks_habarovsk_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
import mainapp.views as mainapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.index, name='index'),
    path('about/', mainapp.about, name='about'),
    path('contact/', mainapp.contact, name='contact'),
    path('staff/', mainapp.staff, name='staff'),
    path('documents/', mainapp.documents, name='documents'),
    path('articles/', mainapp.articles, name='articles'),
    path('article_details/<slug:pk>', mainapp.article_details, name='article_details'),
    path('news/', mainapp.news, name='news'),
    path('detailview/<slug:content>/<slug:pk>',
         mainapp.details, name='detailview'),
    path('create/<slug:content_type>', mainapp.create_factory, name='create'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('messages/', mainapp.messages, name='messages'),
    path('service/<slug:pk>', mainapp.services, name="service"),
    path('reestrsp/', mainapp.reestrsp, name='reestrsp'),
    path('import_profile/', mainapp.import_profile, name='import_proflie'),
    path('accept_order/', mainapp.accept_order, name="accept_order"),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mainapp/models.py
"""
File: models.py
Email: yourname@email.com
Description: models to site project
"""
import os
from django.db import models
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField
from django.core.validators import FileExtensionValidator
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from django.urls import reverse
#using this as a store for weld orgs:
from picklefield.fields import PickledObjectField
# from django_resized import ResizedImageField


# Create your models here.
class Tag(models.Model):

    name = models.CharField(max_length=64)

    class Meta:
        verbose_name = "Тэг"
        verbose_name_plural = "Тэги"

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class Category(models.Model):
    """category model class"""
    name = models.CharField(max_length=64)

    class Meta:
        verbose_name = "Раздел"
        verbose_name_plural = "Разделы"

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class ContentMixin(models.Model):
    '''base class for Post, Article and Documents'''
    title = models.CharField(u'Название', max_length=200)
    url_code = models.CharField(u'Код ссылки', max_length=30, blank=True, default='НЕ УКАЗАН')
    short_description = models.CharField(
        u'Краткое описание', max_length=200, blank=True)
    tags = models.ManyToManyField(Tag, verbose_name='Тэги')
    published_date = models.DateTimeField(
        u'Дата публикации', blank=True, null=True)
    created_date = models.DateTimeField(u'Дата создания', default=timezone.now)
    text = RichTextUploadingField(verbose_name='Текст')
    author = models.ForeignKey(
        'auth.User', verbose_name='Автор', on_delete=models.CASCADE)
    publish_on_main_page = models.BooleanField(
        verbose_name="Опубликовать на главной", default=False)

    class Meta:
        abstract = True

class SidePanel(models.Model):
    title = models.CharField(u'Название', max_length=200)
    text = RichTextUploadingField(verbose_name='Текст')

    class Meta:
        verbose_name = 'Боковая панель'
        verbose_name_plural = 'Боковые панели'

    def __str__(self):
        return self.title


class Post(ContentMixin):
    '''child of contentmixin'''
    category = models.ForeignKey(
        Category, verbose_name='Категория', on_delete=models.CASCADE)
    publish_on_news_page = models.BooleanField(
        verbose_name="Опубликовать в ленте новостей", default=False)
    publish_in_basement=models.BooleanField(u'Опубликовать в подвале на главной', default=False)
    side_panel = models.ForeignKey(SidePanel, verbose_name='Боковая панель', blank=True,
                                    null=True, default=None, on_delete=models.SET_NULL)

    class Meta:
        ordering = ['created_date']
        get_latest_by = ['created_date']
        verbose_name = 'Страница'
        verbose_name_plural = "Страницы"

    def get_absolute_url(self):
        return reverse("detailview",
                       kwargs={"content": "post", "pk": self.pk})

    def publish(self):
        """unused function"""
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Article(ContentMixin):
    '''child of ContentMixin'''

    class Meta:
        ordering = ['created_date']
        get_latest_by = ['created_date']
        verbose_name = 'Статья'
        verbose_name_plural = "Статьи"

    def publish(self):
        """unused, left for future"""
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class DocumentCategory(models.Model):
    name = models.CharField(u'Название категории', max_length=64)
    number = models.SmallIntegerField(verbose_name='Порядок сортировки',
                                    null=True, blank=True, default=None)

    class Meta:
        verbose_name = "Категория документа"
        verbose_name_plural = "Категории документов"

    def __str__(self):
        return self.name

class Document(models.Model):
    """"
    эта модель используется для
    загрузки документов в базу данных
    """
    title = models.CharField(u'Название', max_length=500)
    document = models.FileField(verbose_name='Документ',
                                upload_to="documents/",
                                validators=[FileExtensionValidator(
                                    allowed_extensions=[
                                        'pdf', 'docx', 'doc', 'jpg', 'jpeg'],
                                    message="Неправильный тип файла, используйте\
                                        PDF, DOCX, DOC, JPG, JPEG")])

    category = models.ForeignKey(DocumentCategory, blank=True, null=True, on_delete=models.SET_NULL)
    url_code = models.CharField(u'Код ссылки', max_length=30, blank=True, default='НЕ УКАЗАН')
    uploaded_at = models.DateTimeField(
        verbose_name='Загружен', default=timezone.now)
    tags = models.ManyToManyField(Tag, verbose_name='Тэги', blank=True)
    created_date = models.DateTimeField(
        default=timezone.now, verbose_name='Дата создания')
    post = models.ForeignKey(Post, verbose_name='Страница',
                             blank=True, default='',
                             on_delete=models.SET_NULL,
                             null=True)
    publish_on_main_page = models.BooleanField(
        verbose_name="Опубиковать на главной", default=False)

    class Meta:
        verbose_name = "Документ"
        verbose_name_plural = "Документы"

    def __str__(self):
        return self.title

    def extension(self):
        name, extension = os.path.splitext(self.document.name)
        return extension


def upload_to(instance, filename):
    """left for future, unused function"""
    filename_base, filename_ext = os.path.splitext(filename)
    return "upload/{post_pk}/{filename}{extension}".format(
        post_pk=instance.pk,
        filename=slugify(filename_base),
        extension=filename_ext.lower(),)


def get_image_filename():
    """unused function, left for future"""
    return 'image_{}'.format(slugify(timezone.now()))


class PostPhoto(models.Model):
    """model to load photos to content page"""
    post = models.ForeignKey(Post, verbose_name=u'новость',
                             related_name='images',
                             on_delete=models.SET_NULL,
                             null=True)
    image = models.ImageField(u'изображение', upload_to="upload/")
    title = models.CharField(u'название', max_length=64,
                             blank=True, default=get_image_filename)
    position = models.PositiveIntegerField(u'Позиция', default=0)

    class Meta:
        verbose_name = "Фото"
        verbose_name_plural = "Фотографии"
        ordering = ['position']

    def __str__(self):
        return '{} - {}'.format(self.post, self.image)


class Message(models.Model):
    """this is the class to use within adapter patter realization"""
    STATUS_LIST = (
        (0, 'new'),
        (1, 'registered'),
        (2, 'added_to_sending_queue'),
        (3, 'notify_sent')
    )
    title = models.CharField(u'Заголовок', max_length=64, blank=True)
    typeof = models.CharField(u'Тип сообщения', max_length=64, blank=True)
    params = models.CharField(u'Параметры сообщения',
                              max_length=512, blank=True)
    sender_email = models.EmailField(
        u'Адрес электронной почты', max_length=64, blank=True)
    sender_phone = models.CharField(u'Телефон', max_length=64, blank=True)
    created_date = models.DateTimeField(
        u'Дата получения', default=timezone.now)
    status = models.IntegerField(u'Статус', default=0, choices=STATUS_LIST)

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

    def __str__(self):
        return self.title

    def set_status(self, status_code):
        # if status_code in STATUS_LIST:
        self.status = status_code


class Contact(models.Model):
    title = models.CharField(u'Название контакта', max_length=64, blank=False)
    description = models.CharField(u'Описание', max_length=200, blank=False)
    email = models.EmailField(
        u'Адрес электронной почты', max_length=64, blank=False)
    phone = models.CharField(u'Телефон', max_length=64, blank=False)
    number = models.SmallIntegerField(u'Порядок вывода на сайт', default=0)

    class Meta:
        verbose_name = "Контакт"
        verbose_name_plural = "Контакты"

    def __str__(self):
        return self.title


class Staff(models.Model):
    photo = models.ImageField(u'Фотография', blank=True)
    name = models.CharField(u'ФИО', max_length=120, blank=False)
    job = models.CharField(u'Должность', max_length=120, blank=False)
    experience = models.CharField(u'Опыт работы', max_length=500, blank=True)
    priority = models.SmallIntegerField(u'Приоритет', default=0)

    class Meta:
        verbose_name = "Сотрудник"
        verbose_name_plural = "Сотрудники"

    def __str__(self):
        return '{} - {}'.format(self.name, self.job)



class Menu(models.Model):
    """linking main page UI elements with its description"""
    url_code = models.CharField(u'Код ссылки', max_length=30)
    title = models.CharField(u'Заголовок ссылки', max_length=60)
    url = models.CharField(u'Адрес ссылки', max_length=200, default="НЕТ")

    class Meta:
        verbose_name = "Ссылка"
        verbose_name_plural = "Ссылки"

    def __str__(self):
        return self.title


class Registry(models.Model):
    """this is the class to load external registry records"""
    STATUS_LIST = ((0, 'new'), (1, 'published'))
    title = models.CharField(u'Название', max_length=64, blank=True)
    org = models.CharField(u'Организация', max_length=120, blank=True)
    typeof = models.CharField(u'Тип', max_length=64, blank=True)

mainapp/forms.py
from django import forms
from django.core.validators import FileExtensionValidator, validate_email
import os
from captcha.fields import CaptchaField
from .models import Post, Article, Document, Menu, Profile, OrderService


class ContentForm(forms.ModelForm):
    """form to use with fabric in news-view"""

    def __init__(self, *args, **kwargs):
        super(forms.ModelForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        fieldset = {
            'post_form_fields': ('title', 'tags', 'category', 'author', 'text',
                                 'created_date', 'published_date'),
            'article_form_fields': ('title', 'tags', 'author', 'text',
                                    'created_date', 'published_date'),
            'document_form_fields': ('title', 'document', 'tags',
                                     'created_date', 'uploaded_at')
        }


class PostForm(ContentForm):

    class Meta(ContentForm.Meta):
        model = Post
        fields = ContentForm.Meta.fieldset['post_form_fields']


class ArticleForm(ContentForm):

    class Meta(ContentForm.Meta):
        model = Article
        fields = ContentForm.Meta.fieldset['article_form_fields']


class DocumentForm(ContentForm):
    ALOWED_TYPES = ['jpg', 'jpeg', 'doc', 'docx', 'pdf', 'xls', 'xlsx']

    class Meta(ContentForm.Meta):
        model = Document
        fields = ContentForm.Meta.fieldset['document_form_fields']


class SendMessageForm(forms.Form):
    name = forms.CharField(max_length=50, widget=forms.TextInput(
        attrs={'class': 'modal__form_input'}))
    phone = forms.CharField(max_length=20, widget=forms.TextInput(
        attrs={'class': 'modal__form_input'}))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'class': 'modal__form_input'}))
    params = forms.CharField(required=False, max_length=128)
    comment = forms.CharField(
        required=False, max_length=256, widget=forms.Textarea(
            attrs={'class': 'modal__form_textarea'}))
    pdata = forms.BooleanField(
        initial=True, required=True, widget=forms.CheckboxInput(
            attrs={'class': 'checkmark'}))


class SubscribeForm(forms.Form):
    email = forms.EmailField(
        required=True, widget=forms.EmailInput(
            attrs={'class': 'main-footer__subscribe-email--input',
                   'placeholder': 'Введите e-mail'}))


class AskQuestionForm(forms.Form):
    name = forms.CharField(max_length=50, widget=forms.TextInput(
        attrs={'class': 'modal__form_input'}))
    phone = forms.CharField(max_length=20, widget=forms.TextInput(
        attrs={'class': 'modal__form_input'}))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'class': 'modal__form_input'}))
    comment = forms.CharField(
        required=False, max_length=256, widget=forms.Textarea(
            attrs={'class': 'modal__form_textarea'}))
    pdata = forms.BooleanField(
        error_messages={
            'required': 'Вы должны принять условия обработки \
            персональных данных в соответствии с 152-ФЗ'},
        initial=True, required=True, widget=forms.CheckboxInput(
            attrs={'class': 'checkmark'}))


class DocumentSearchForm(forms.Form):
    document_name = forms.CharField(max_length=50, required=False, widget=forms.TextInput(
        attrs={'class': 'form-control',
               'placeholder': 'Введите название документа'}
    ))

class SearchRegistryForm(forms.Form):
    fio = forms.CharField(max_length=64, required=False, widget=forms.TextInput(
        attrs={'class': 'form__subject__search'}))
    work_place = forms.CharField(max_length=64, required=False, widget=forms.TextInput(
        attrs={'class': 'form__subject__search'}))

class ProfileImportForm(forms.Form):
    """form for profile import file"""
    file = forms.FileField(allow_empty_file=True, required=False)

    # def clean(self):
    #     document = self.cleaned_data.get('document', None)
    #     if not document:
    #         raise forms.ValidationError('Missing document file')
    #     try:
    #         extension = os.path.splitext(document.name)[1][1:].lower()
    #         if extension in self.ALOWED_TYPES:
    #             return document
    #         else:
    #             raise forms.ValidationError('File types is not allowed')
    #     except Exception as e:
    #         raise forms.ValidationError('Can not identify file type')


class OrderForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = OrderService
        fields = ['name', 'phone', 'compound']
        widgets = {
                'name': forms.TextInput({
                'placeholder': "Ваше имя",
                'class': 'form-control form-control-sm',
                }),
                'phone': forms.TextInput({
                    'placeholder': 'Ваш телефон',
                    'class': 'form-control form-control-sm',
                    'type': 'text',
                }),
                # <input type="text" class="form-control form-control-sm" placeholder=""  type="text" id="phone2" required="">
            }

mainapp/templates/mainapp/includes/admin_panel.html
{% comment %} this is admin panel {% endcomment %}
{% if user.is_authenticated %}
<div class="container">
    <div class="admin_panel row bg-light p-3">

        <div class="col-5">
            <form enctype="multipart/form-data" method="post" action="/import_profile/">
                {% csrf_token %}

                <div class="row align-items-center">
                    <div class="col-lg-6">Загрузка профиля из файла
                        {{ profile_import_form.file }}

                        <div><a href="media/import_file_example.txt" download>Скачать</a> образец файла импорта</div>

                    </div>
                    <div class="col-lg-6">
                        <button class="btn btn-primary btn-sm">Загрузить</button>
                    </div>

                </div>
            </form>
            {% comment %} <a href="#" class="btn btn-light btn-sm">Загрузить файл импорта</a>
            <a href="#" class="btn btn-outline-light btn-sm">Пример файла</a> {% endcomment %}
        </div>
        <div class="offset-lg-4 col-lg-3 text-center">
            <a class="btn btn-link btn-sm" target="_blank" href="/admin/"><i class="fas fa-user"></i>&nbsp;Админка
                сайта</a>
            <a class="btn btn-link btn-sm" href="/accounts/logout/"><i class="fas fa-sign-out-alt"> </i>&nbsp;Выйти</a>
        </div>
    </div>
</div>
{% endif %}

mainapp/templates/mainapp/includes/articles.html
<div class="section-block mb-5">
{% if articles %}
{% for article in articles %}
    <div class="section p-3 p-sm-4 mb-4">
        <p class="text-size-20 mb-3 mb-lg-4">{{ article.title }}</p>
        <div class="row">
            <div class="col-6"><small>{{ article.published_date|date:"d M. Y"}}</small></div>
            <div class="col-6 text-right"><a href="{% url 'detailview' 'article' article.pk %}#page-top" class="btn btn-outline-purple btn-sm">Читать
                    →</a></div>
        </div>
    </div>
{% endfor %}
{% else %}
    <div class="section p-3 p-sm-4 mb-4">
        <p class="text-size-20 mb-3 mb-lg-4">Применение СМТ технологий при сварке</p>
        <div class="row">
            <div class="col-6"><small>08 Июля 2018</small></div>
            <div class="col-6 text-right"><a href="#" class="btn btn-outline-purple btn-sm">Читать
                    →</a></div>
        </div>
    </div>
    <div class="section p-3 p-sm-4 mb-4">
        <p class="text-size-20 mb-3 mb-lg-4">Соединение разнородных материалов</p>
        <div class="row">
            <div class="col-6"><small>05 Июля 2018</small></div>
            <div class="col-6 text-right"><a href="#" class="btn btn-outline-purple btn-sm">Читать
                    →</a></div>
        </div>
    </div>
</div>
{% endif %}

mainapp/templates/mainapp/includes/documents.html
{% load static %}
{% if docs %}
    {% for item in docs %}
    <div class="doc p-3 p-sm-4 mb-4">
        <p class="font-text-medium text-size-14 mb-3 mb-xl-4">
            {% for tag in item.tags.all %} 
            <i class="far fa-file">&nbsp;</i>{{ tag.name }}
            {% endfor %} 
        </p>
        <div class="row align-items-center">
            <div class="col-2"><img src="{% static 'images/img-icon-doc.png' %}" alt="Icon doc" class="img-fluid"></div>
            <div class="col"><a href="{{ item.document.url }}" class="d-block font-text-thin text-size-14" target="_blank">
            {{ item.title }}</a></div>
        </div>
    </div>
    {% endfor %}
{% else %}
<div class="doc p-3 p-sm-4 mb-4">
    <p class="font-text-medium text-size-14 mb-3 mb-xl-4">Руководящие документы</p>
    <div class="row align-items-center">
        <div class="col-2"><img src="static/images/img-icon-doc.png" alt="Icon doc" class="img-fluid"></div>
        <div class="col"><a href="#" class="d-block font-text-thin text-size-14" target="_blank">Перечень
                групп технических устройств опасных производственных объектов</a></div>
    </div>
</div>
<div class="doc p-3 p-sm-4 mb-4">
    <p class="font-text-medium text-size-14 mb-3 mb-xl-4">Руководящие документы</p>
    <div class="row align-items-center">
        <div class="col-2"><img src="static/images/img-icon-doc.png" alt="Icon doc" class="img-fluid"></div>
        <div class="col"><a href="#" class="d-block font-text-thin text-size-14" target="_blank">Перечень
                групп технических устройств опасных производственных объектов</a></div>
    </div>
</div>
{% endif %}

mainapp/templates/mainapp/includes/documents_side_panel.html
        {% for category in document_categories %}
        <div class="col-sm">
            <div class="mb-3 mb-sm-0">
            <p class="text-size-14 mb-2 mb-sm-3">{{ category.name }}</p>

            {% for document in documents %}
                {% if document.category == category %}
                <p class="mb-1"><a href="{{ document.document.url }}" download="">{{ document.title }}</a></p>
                {% endif %}
            {% endfor %}

            </div>
        </div>
        {% endfor %}

mainapp/templates/mainapp/includes/modal-windows.html
{% load static %}
<!-- Модальное окно - Оставить заявку -->
<div class="modal fade" id="modal-statement" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="pt-0 pt-sm-4 pt-xl-5">
                <div class="modal-header px-3 px-sm-5">
                    <h5 class="modal-title mb-3" id="">Оставить заявку</h5>
                    <div class="row">
                        <div class="col col-sm-10 col-xl-6">
                            <p class="font-text-thin">Выберите вид заявки, введите свои контактные данные, и наш специалист свяжется с вами в ближайшее время</p>
                        </div>
                    </div>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>

            <form id="order_form">
                {% csrf_token %}
                <div class="modal-body px-3 px-sm-5">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="id_name" class="col-form-label col-form-label-sm">Имя</label>
                                {% comment %} <input type="text" class="form-control form-control-sm" id="" required=""> {% endcomment %}
                                {{ order_form.name }}
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="id_phone" class="col-form-label col-form-label-sm">Номер телефона</label>
                                {% comment %} <input type="text" class="form-control form-control-sm" id="" required=""> {% endcomment %}
                                {{ order_form.phone }}
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group ">
                                <label for="" class="col-form-label col-form-label-sm">Вид заявки</label>
                                <select name="order_type" class="form-control form-control-sm">
                                    <option value="att_sv">Аттестация сварщиков</option>
                                    <option value="att_sp_sv">Аттестация специалистов сварочного производства</option>
                                    <option value="att_sm">Аттестация сварочного оборудования</option>
                                    <option value="att_so">Аттестация сварочных материалов</option>
                                    <option value="att_st">Аттестация сварочных технологий</option>
                                    <option value="ocenka_qual">Оценка квалификации в области сварки и контроля</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="soglasie" required="">
                        <label class="custom-control-label text-white" for="soglasie"><small>Я даю <a href="#" class="text-white" target="_blank">согласие на обработку персональных данных</a></small></label>
                    </div>
                    <div id="order_captcha_check">
                        {{ order_form.captcha }}
                        <div id="order_captcha_message"></div>
                    </div>
                </div>
                <div class="modal-footer pb-5 px-3 px-sm-5">
                    <button id="order_service_button" type="submit" class="btn btn-blue">Отправить заявку</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- End Набор в группу аттестации -->

<!-- Модальное окно - Задать вопрос -->
<div class="modal fade" id="modal-question" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="pt-0 pt-sm-4 pt-xl-5">
                <div class="modal-header px-3 px-sm-5">
                    <h5 class="modal-title mb-3" id="">Задать вопрос</h5>
                    <div class="row">
                        <div class="col col-sm-10 col-xl-6">
                            <p class="font-text-thin">Вы можете задать любой вопрос и наш специалист ответит вам в ближайшее время</p>
                        </div>
                    </div>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
            <form>
                <div class="modal-body px-3 px-sm-5">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="" class="col-form-label col-form-label-sm">Имя</label>
                                <input type="text" class="form-control form-control-sm" id="" required="">
                            </div>
                            <div class="form-group">
                                <label for="" class="col-form-label col-form-label-sm">Номер телефона</label>
                                <input type="text" class="form-control form-control-sm" id="" required="">
                            </div>
                        </div>
                        <!-- <div class="col-sm-6">
                            <div class="form-group">
                                <label for="" class="col-form-label col-form-label-sm">Номер телефона</label>
                                <input type="text" class="form-control form-control-sm" id="" required="">
                            </div>
                        </div> -->
                        <div class="col-sm-6">
                            <div class="form-group ">
                                <label for="" class="col-form-label col-form-label-sm">Ваш вопрос</label>
                                <textarea name="" class="form-control form-control-sm" rows="6" id="" required=""></textarea>
                                <!-- <select class="form-control form-control-sm">
                                    <option>Аттестация сварщиков</option>
                                    <option>Аттестация специалистов сварочного производства</option>
                                    <option>Аттестация сварочного оборудования</option>
                                    <option>Аттестация сварочных материалов</option>
                                    <option>Аттестация сварочных технологий</option>
                                    <option>Оценка квалификации</option>
                                </select> -->
                            </div>
                        </div>
                    </div>

                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="soglasie" required="">
                        <label class="custom-control-label text-white" for="soglasie"><small>Я даю <a href="#" class="text-white" target="_blank">согласие на обработку персональных данных</a></small></label>
                    </div>

                    <!-- <p class="text-secondary">Вы можете задать любой вопрос и наш специалист ответит вам в ближайшее время</p>
                    <div class="form-group">
                        <label for="" class="col-form-label col-form-label-sm">Ваше имя</label>
                        <input type="text" class="form-control form-control-sm" id="" required="">
                    </div>
                    <div class="form-group mb-4">
                        <label for="" class="col-form-label col-form-label-sm">Ваш номер телефона</label>
                        <input type="text" class="form-control form-control-sm" id="" required="">
                    </div>
                    <div class="form-group mb-4">
                        <label for="" class="col-form-label col-form-label-sm">Задать вопрос</label>
                        <textarea name="" class="form-control form-control-sm" id="" placeholder="Ваш вопрос" required=""></textarea>
                    </div>
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="obratka" required="">
                        <label class="custom-control-label text-secondary" for="obratka"><small>Даю <a href="#" class="text-secondary" target="_blank">согласие на обработку персональных данных</a></small></label>
                    </div> -->
                </div>
                <div class="modal-footer pb-5 px-3 px-sm-5">
                    <button type="submit" class="btn btn-blue">Отправить</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- End Задать вопрос -->

mainapp/templates/mainapp/includes/one_article.html
                <div class="section p-3 p-sm-4">
                    <p class="text-size-20 mb-3 mb-lg-4">{{ article.title }}</p>
                    <div class="row">
                        <div class="col-6"><small>{{ article.published_date }}</small></div>
                        <div class="col-6 text-right"><a href="{% url 'article_details' article.pk %}#page-top" class="btn btn-outline-purple btn-sm">Читать  →</a></div>
                    </div>
                </div>